# /ADK/src/lib/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

# XXX should have multiple builds for all supported targets
ADK_PLATFORM = native
ADK_APP_TYPE = lib
ADK_APP_NAME = adk
ADK_USE_PYTHON = yes
ADK_NO_ADK_LIB = yes
ADK_USE_GUI = yes

include $(ADK_ROOT)/make/make.mk
