# This file is a part of ADK library.
# Copyright (c) 2012-2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See LICENSE file for copyright details.

import adk

adk.Conf(APP_NAME= 'desktop_gui',
         APP_TYPE = 'app',
         APP_ALIAS = 'desktop_gui_sample',
         LIBS = 'desktop_sample_gui',
         RES_FILES = 'props.xml',
         SUBDIRS = 'lib').Build()
