# /ADK/samples/desktop_console/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_PLATFORM = native
ADK_APP_TYPE = app
ADK_APP_NAME = desktop_sample_console
ADK_USE_GUI = no

include $(ADK_ROOT)/make/make.mk
