# This file is a part of ADK library.
# Copyright (c) 2012-2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

conf = adk.Conf(APP_NAME= 'desktop_console',
                APP_TYPE = 'app',
                APP_ALIAS = 'desktop_console_sample',
                USE_GUI = False).Build()
