# /ADK/samples/unit_test/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2013, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_APP_TYPE = unit_test

ADK_TEST_NAME = sample_test
ADK_TEST_DESC = Sample ADK unit test

ADK_TEST_SRCS = $(wildcard component/*.cpp)

include $(ADK_ROOT)/make/make.mk
