# This file is a part of ADK library.
# Copyright (c) 2012-2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

adk.Conf(APP_TYPE = 'unit_test',
         APP_NAME = 'sample_test',
         TEST_DESC = 'Sample ADK unit test',
         TEST_SRCS = Glob('component/*.cpp')).Build()
