# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

conf = adk.Conf(
    APP_NAME= 'avr_sample_1',
    APP_TYPE = 'app',
    PLATFORM = 'avr',
                
    # MCU code name
    AVR_MCU = 'attiny2313',
    # Programmer type
    PROGRAMMER = 'avrisp2',
    # Programmer connection
    PROGRAMMER_BUS = '/dev/ttyUSB0',
    # MCU clock frequency in Hz
    MCU_FREQ = 20000000,
    
    # L 0b11011111 H 0b11011111- 20MHz, BOD 2.7V
    MCU_LFUSE = 0xdf,
    MCU_HFUSE = 0xdb,

    # Make USB device
    AVR_USE_USB = True,
    
    # Additional directory with source files
    SRC_DIRS = 'pwm',
    # Additional source file
    SRCS = 'misc/misc.c',
    # Additional include directories
    INCLUDE_DIRS = '. ../include misc',
    # Additional defines
    DEFS = 'AVR_USB_DEBUG'
                
    ).Build()
