# /ADK/doc/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_APP_TYPE = doc
ADK_DOC_NAMESPACE = adk
ADK_DOC_DIR = /var/www/projects_doc/data

include $(ADK_ROOT)/make/make.mk
