# This file is a part of ADK library.
# Copyright (c) 2012-2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

conf = adk.Conf(APP_TYPE = 'unit_test',
                APP_NAME = 'multithreading',
                TEST_DESC = 'Multithreading',
                TEST_SRCS = Glob('#/src/lib/*.cpp'),
                USE_GUI = True).Build()
