# /ADK/samples/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2013, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = avr desktop_console desktop_gui unit_test

include $(ADK_ROOT)/make/make.mk
