# /ADK/samples/desktop/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = lib

ADK_PLATFORM = native
ADK_APP_TYPE = app
ADK_APP_NAME = desktop_sample_1

LIBS += desktop_sample_2
LIB_DIRS += lib/build/$(ADK_PLATFORM)-$(ADK_BUILD_TYPE)

include $(ADK_ROOT)/make/make.mk
