# /ADK/unittest/bitmap/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2013, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_APP_TYPE = unit_test

ADK_TEST_NAME = bitmap
ADK_TEST_DESC = Bitmap functionality

INCLUDE_DIRS += $(DESKTOP_LIBS_INC_DIRS)
LIBS += $(DESKTOP_LIBS)

include $(ADK_ROOT)/make/make.mk
