# /ADK/unittest/misc/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_APP_TYPE = unit_test

ADK_TEST_NAME = miscelaneous
ADK_TEST_DESC = Miscelaneous features

ADK_TEST_SRCS = $(wildcard $(ADK_ROOT)/src/lib/*.cpp)

include $(ADK_ROOT)/make/make.mk
