# /ADK/samples/desktop/lib/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_PLATFORM = native
ADK_APP_TYPE = lib
ADK_APP_NAME = desktop_sample_gui

include $(ADK_ROOT)/make/make.mk
