# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

conf = adk.Conf(APP_NAME= 'desktop_sample_gui',
                APP_TYPE = 'dynamic_lib',
                APP_ALIAS = 'desktop_gui_sample_lib',
                INSTALL_DIR = '${ADK_PREFIX}/lib',
                USE_GUI = True).Build()
