# /ADK/unittest/xml/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_APP_TYPE = unit_test

ADK_TEST_NAME = xml
ADK_TEST_DESC = XML manipulation functionality

ADK_TEST_SRCS = $(wildcard $(ADK_ROOT)/src/lib/*.cpp)

RES_FILES += test.xml

include $(ADK_ROOT)/make/make.mk
