# /ADK/samples/avr/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = firmware client

include $(ADK_ROOT)/make/make.mk
