# /ADK/samples/avr/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_PLATFORM = avr
ADK_APP_TYPE = app
ADK_APP_NAME = avr_sample_1

SRC_DIRS = pwm

include $(ADK_ROOT)/make/make.mk
