# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

conf = adk.Conf(APP_TYPE = 'unit_test',
                APP_NAME = 'properties',
                TEST_DESC = 'Properties framework',
                RES_FILES = 'test_props.xml',
                TEST_SRCS = Glob('#/src/lib/*.cpp'),
                AVR_USE_USB = True,
                USE_GUI = True).Build()
