# This file is a part of ADK library.
# Copyright (c) 2012-2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

adk.Conf(APP_TYPE = 'unit_test',
         APP_NAME = 'properties',
         TEST_DESC = 'Properties framework',
         RES_FILES = 'test_props.xml',
         TEST_SRCS = Glob('#/src/lib/*.cpp'),
         USE_GUI = True).Build()
