# /ADK/samples/avr/client/Makefile
#
# This file is a part of ADK library.
# Copyright (c) 2012-2014, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

ADK_PLATFORM = native
ADK_APP_TYPE = app
ADK_APP_NAME = avr_usb_sample
ADK_USE_GUI = no
ADK_AVR_USE_USB = yes

INCLUDE_DIRS = ../include

include $(ADK_ROOT)/make/make.mk
