# This file is a part of ADK library.
# Copyright (c) 2012-2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import adk

adk.Conf(APP_NAME= 'avr_usb_sample',
         APP_TYPE = 'app',
         USE_GUI = False,
         AVR_USE_USB = True,
         INCLUDE_DIRS = '../include').Build()
